config/routes.rb
Rails.application.routes.draw do
  resources :stations
  # Define your application routes per the DSL in https://guides.rubyonrails.org/routing.html

  # Reveal health status on /up that returns 200 if the app boots with no exceptions, otherwise 500.
  # Can be used by load balancers and uptime monitors to verify that the app is live.
  get "up" => "rails/health#show", as: :rails_health_check

  # Defines the root path route ("/")
   root "home#index"
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  primary_abstract_class
end

app/models/station.rb
class Station < ApplicationRecord
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
end

app/controllers/home_controller.rb
class HomeController < ApplicationController
  def index
  end
end

app/controllers/stations_controller.rb
class StationsController < ApplicationController
  before_action :set_station, only: %i[ show edit update destroy ]

  # GET /stations or /stations.json
  def index
    @stations = Station.first(50)
  end

  # GET /stations/1 or /stations/1.json
  def show
  end

  # GET /stations/new
  def new
    @station = Station.new
  end

  # GET /stations/1/edit
  def edit
  end

  # POST /stations or /stations.json
  def create
    @station = Station.new(station_params)

    respond_to do |format|
      if @station.save
        format.html { redirect_to station_url(@station), notice: "Station was successfully created." }
        format.json { render :show, status: :created, location: @station }
      else
        format.html { render :new, status: :unprocessable_entity }
        format.json { render json: @station.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /stations/1 or /stations/1.json
  def update
    respond_to do |format|
      if @station.update(station_params)
        format.html { redirect_to station_url(@station), notice: "Station was successfully updated." }
        format.json { render :show, status: :ok, location: @station }
      else
        format.html { render :edit, status: :unprocessable_entity }
        format.json { render json: @station.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /stations/1 or /stations/1.json
  def destroy
    @station.destroy!

    respond_to do |format|
      format.html { redirect_to stations_url, notice: "Station was successfully destroyed." }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_station
      @station = Station.find(params[:id])
    end

    # Only allow a list of trusted parameters through.
    def station_params
      params.require(:station).permit(:id_station, :latitude, :longitude, :cp, :pop, :adresse, :ville, :services, :prix, :horaires, :geom, :gazole_maj, :gazole_prix, :sp95_maj, :sp95_prix, :e85_maj, :e85_prix, :gplc_maj, :gplc_prix, :e10_maj, :e10_prix, :sp98_maj, :sp98_prix, :carburants_disponibles, :carburants_indisponibles, :horaires_automate_24_24, :services_service, :departement, :code_departement, :region, :code_region)
    end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/home_helper.rb
module HomeHelper
end

app/helpers/stations_helper.rb
module StationsHelper
end

app/views/home/index.html.erb
<h1>Home#index</h1>
<p>Find me in app/views/home/index.html.erb</p>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>ComparateurCarburants</title>
    <meta name="viewport" content="width=device-width,initial-scale=1">
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag "application", "data-turbo-track": "reload" %>
    <%= javascript_include_tag "application", "data-turbo-track": "reload", defer: true %>
  </head>

  <body>
    <%= yield %>
  </body>
</html>

app/views/stations/_form.html.erb
<%= form_with(model: station) do |form| %>
  <% if station.errors.any? %>
    <div style="color: red">
      <h2><%= pluralize(station.errors.count, "error") %> prohibited this station from being saved:</h2>

      <ul>
        <% station.errors.each do |error| %>
          <li><%= error.full_message %></li>
        <% end %>
      </ul>
    </div>
  <% end %>

  <div>
    <%= form.label :id_station, style: "display: block" %>
    <%= form.number_field :id_station %>
  </div>

  <div>
    <%= form.label :latitude, style: "display: block" %>
    <%= form.text_field :latitude %>
  </div>

  <div>
    <%= form.label :longitude, style: "display: block" %>
    <%= form.text_field :longitude %>
  </div>

  <div>
    <%= form.label :cp, style: "display: block" %>
    <%= form.text_field :cp %>
  </div>

  <div>
    <%= form.label :pop, style: "display: block" %>
    <%= form.text_field :pop %>
  </div>

  <div>
    <%= form.label :adresse, style: "display: block" %>
    <%= form.text_field :adresse %>
  </div>

  <div>
    <%= form.label :ville, style: "display: block" %>
    <%= form.text_field :ville %>
  </div>

  <div>
    <%= form.label :services, style: "display: block" %>
    <%= form.text_field :services %>
  </div>

  <div>
    <%= form.label :prix, style: "display: block" %>
    <%= form.text_field :prix %>
  </div>

  <div>
    <%= form.label :horaires, style: "display: block" %>
    <%= form.text_field :horaires %>
  </div>

  <div>
    <%= form.label :geom, style: "display: block" %>
    <%= form.text_field :geom %>
  </div>

  <div>
    <%= form.label :gazole_maj, style: "display: block" %>
    <%= form.text_field :gazole_maj %>
  </div>

  <div>
    <%= form.label :gazole_prix, style: "display: block" %>
    <%= form.text_field :gazole_prix %>
  </div>

  <div>
    <%= form.label :sp95_maj, style: "display: block" %>
    <%= form.text_field :sp95_maj %>
  </div>

  <div>
    <%= form.label :sp95_prix, style: "display: block" %>
    <%= form.text_field :sp95_prix %>
  </div>

  <div>
    <%= form.label :e85_maj, style: "display: block" %>
    <%= form.text_field :e85_maj %>
  </div>

  <div>
    <%= form.label :e85_prix, style: "display: block" %>
    <%= form.text_field :e85_prix %>
  </div>

  <div>
    <%= form.label :gplc_maj, style: "display: block" %>
    <%= form.text_field :gplc_maj %>
  </div>

  <div>
    <%= form.label :gplc_prix, style: "display: block" %>
    <%= form.text_field :gplc_prix %>
  </div>

  <div>
    <%= form.label :e10_maj, style: "display: block" %>
    <%= form.text_field :e10_maj %>
  </div>

  <div>
    <%= form.label :e10_prix, style: "display: block" %>
    <%= form.text_field :e10_prix %>
  </div>

  <div>
    <%= form.label :sp98_maj, style: "display: block" %>
    <%= form.text_field :sp98_maj %>
  </div>

  <div>
    <%= form.label :sp98_prix, style: "display: block" %>
    <%= form.text_field :sp98_prix %>
  </div>

  <div>
    <%= form.label :carburants_disponibles, style: "display: block" %>
    <%= form.text_field :carburants_disponibles %>
  </div>

  <div>
    <%= form.label :carburants_indisponibles, style: "display: block" %>
    <%= form.text_field :carburants_indisponibles %>
  </div>

  <div>
    <%= form.label :horaires_automate_24_24, style: "display: block" %>
    <%= form.text_field :horaires_automate_24_24 %>
  </div>

  <div>
    <%= form.label :services_service, style: "display: block" %>
    <%= form.text_field :services_service %>
  </div>

  <div>
    <%= form.label :departement, style: "display: block" %>
    <%= form.text_field :departement %>
  </div>

  <div>
    <%= form.label :code_departement, style: "display: block" %>
    <%= form.text_field :code_departement %>
  </div>

  <div>
    <%= form.label :region, style: "display: block" %>
    <%= form.text_field :region %>
  </div>

  <div>
    <%= form.label :code_region, style: "display: block" %>
    <%= form.text_field :code_region %>
  </div>

  <div>
    <%= form.submit %>
  </div>
<% end %>

app/views/stations/_station.html.erb
<div id="<%= dom_id station %>">
  <p>
    <strong>Id station:</strong>
    <%= station.id_station %>
  </p>

  <p>
    <strong>Latitude:</strong>
    <%= station.latitude %>
  </p>

  <p>
    <strong>Longitude:</strong>
    <%= station.longitude %>
  </p>

  <p>
    <strong>Cp:</strong>
    <%= station.cp %>
  </p>

  <p>
    <strong>Pop:</strong>
    <%= station.pop %>
  </p>

  <p>
    <strong>Adresse:</strong>
    <%= station.adresse %>
  </p>

  <p>
    <strong>Ville:</strong>
    <%= station.ville %>
  </p>

  <p>
    <strong>Services:</strong>
    <%= station.services %>
  </p>

  <p>
    <strong>Prix:</strong>
    <%= station.prix %>
  </p>

  <p>
    <strong>Horaires:</strong>
    <%= station.horaires %>
  </p>

  <p>
    <strong>Geom:</strong>
    <%= station.geom %>
  </p>

  <p>
    <strong>Gazole maj:</strong>
    <%= station.gazole_maj %>
  </p>

  <p>
    <strong>Gazole prix:</strong>
    <%= station.gazole_prix %>
  </p>

  <p>
    <strong>Sp95 maj:</strong>
    <%= station.sp95_maj %>
  </p>

  <p>
    <strong>Sp95 prix:</strong>
    <%= station.sp95_prix %>
  </p>

  <p>
    <strong>E85 maj:</strong>
    <%= station.e85_maj %>
  </p>

  <p>
    <strong>E85 prix:</strong>
    <%= station.e85_prix %>
  </p>

  <p>
    <strong>Gplc maj:</strong>
    <%= station.gplc_maj %>
  </p>

  <p>
    <strong>Gplc prix:</strong>
    <%= station.gplc_prix %>
  </p>

  <p>
    <strong>E10 maj:</strong>
    <%= station.e10_maj %>
  </p>

  <p>
    <strong>E10 prix:</strong>
    <%= station.e10_prix %>
  </p>

  <p>
    <strong>Sp98 maj:</strong>
    <%= station.sp98_maj %>
  </p>

  <p>
    <strong>Sp98 prix:</strong>
    <%= station.sp98_prix %>
  </p>

  <p>
    <strong>Carburants disponibles:</strong>
    <%= station.carburants_disponibles %>
  </p>

  <p>
    <strong>Carburants indisponibles:</strong>
    <%= station.carburants_indisponibles %>
  </p>

  <p>
    <strong>Horaires automate 24 24:</strong>
    <%= station.horaires_automate_24_24 %>
  </p>

  <p>
    <strong>Services service:</strong>
    <%= station.services_service %>
  </p>

  <p>
    <strong>Departement:</strong>
    <%= station.departement %>
  </p>

  <p>
    <strong>Code departement:</strong>
    <%= station.code_departement %>
  </p>

  <p>
    <strong>Region:</strong>
    <%= station.region %>
  </p>

  <p>
    <strong>Code region:</strong>
    <%= station.code_region %>
  </p>

</div>

app/views/stations/edit.html.erb
<h1>Editing station</h1>

<%= render "form", station: @station %>

<br>

<div>
  <%= link_to "Show this station", @station %> |
  <%= link_to "Back to stations", stations_path %>
</div>

app/views/stations/index.html.erb
<p style="color: green"><%= notice %></p>

<h1>Stations</h1>

<div id="stations">
  <% @stations.each do |station| %>
    <%= render station %>
    <p>
      <%= link_to "Show this station", station %>
    </p>
  <% end %>
</div>

<%= link_to "New station", new_station_path %>

app/views/stations/new.html.erb
<h1>New station</h1>

<%= render "form", station: @station %>

<br>

<div>
  <%= link_to "Back to stations", stations_path %>
</div>

app/views/stations/show.html.erb
<p style="color: green"><%= notice %></p>

<%= render @station %>

<div>
  <%= link_to "Edit this station", edit_station_path(@station) %> |
  <%= link_to "Back to stations", stations_path %>

  <%= button_to "Destroy this station", @station, method: :delete %>
</div>